#!/bin/sh

export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="firefox"

# XDG spec and cleanup
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export LESSHISTFILE="-"
export HISTFILE="${XDG_DATA_HOME:-$HOME/.local/share}/history"

export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"

export CARGO_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/cargo"
export GOPATH="${XDG_DATA_HOME:-$HOME/.local/share}/go"

